/*
 * File: app/controller/Customer.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.Customer', {
    extend: 'Ext.app.Controller',

    refs: [
        {
            ref: 'customerDetail',
            selector: '.mainview form'
        }
    ],

    onGridpanelItemClick: function(tablepanel, record, item, index, e, options) {
        var form = this.getCustomerDetail();

        form.loadRecord(record);
    },

    onSaveClick: function(button, e, options) {
        var form = this.getCustomerDetail(),
        values = form.getValues(),
        record = form.getRecord();

        record.beginEdit();

        record.set(values);

        if (record.isValid()) {
            record.endEdit();

            record.save();
        }
        else {
            record.cancelEdit();

            Ext.Msg.alert("Error", "There are errors with the record.");
        }
    },

    init: function(application) {
        this.control({
            ".mainview grid": {
                itemclick: this.onGridpanelItemClick
            },
            "[action=Save]": {
                click: this.onSaveClick
            }
        });
    }

});
