/*
 * File: app/store/Customers.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.Customers', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.Customer'
    ],

    config: {
        autoLoad: true,
        model: 'MyApp.model.Customer',
        storeId: 'Customers',
        proxy: {
            type: 'ajax',
            url: 'http://192.168.0.24:51266/api/customer',
            reader: {
                type: 'json'
            }
        },
        grouper: {
            groupFn: function(record) {
                return record.get("company")[0];
            }
        },
        sorters: {
            property: 'company'
        }
    }
});