/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MainView', {
    extend: 'Ext.window.Window',
    alias: 'widget.mainview',

    height: 522,
    hidden: false,
    width: 776,
    layout: {
        align: 'stretch',
        type: 'hbox'
    },
    title: 'Customers to Visit',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'gridpanel',
                    flex: 1,
                    store: 'Customers',
                    viewConfig: {
                        border: false
                    },
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            width: 170,
                            dataIndex: 'company',
                            text: 'Company'
                        },
                        {
                            xtype: 'gridcolumn',
                            dataIndex: 'notes',
                            flex: 1,
                            text: 'Notes'
                        }
                    ]
                },
                {
                    xtype: 'form',
                    flex: 1,
                    bodyPadding: 10,
                    items: [
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            name: 'company',
                            fieldLabel: 'Company'
                        },
                        {
                            xtype: 'textareafield',
                            anchor: '100%',
                            name: 'notes',
                            fieldLabel: 'Notes'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'toolbar',
                            dock: 'top',
                            items: [
                                {
                                    xtype: 'button',
                                    action: 'Save',
                                    text: 'Save'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});